repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8

  - repo: https://github.com/timothycrosley/isort
    rev: 5.4.2
    hooks:
      - id: isort
        additional_dependencies: [toml]
        exclude: ^.*/?setup\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: master  # or specific git tag
    hooks:
      - id: markdownlint # Configure in .mdlrc
    #- id: bundler-audit
    #- id: check-mailmap
    #- id: fasterer
    #- id: forbid-binary
    #- id: forbid-space-in-indent
    #- id: git-check  # Configure in .gitattributes
    #- id: git-dirty  # Configure in .gitignore
    #- id: reek
    #- id: require-ascii
    #- id: rubocop
    #- id: script-must-have-extension
    #- id: script-must-not-have-extension
    #- id: shellcheck
    #- id: shfmt
